import "./styles/globals.css";
import type { Metadata } from "next";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
import { Red_Hat_Text } from "next/font/google";
const fontFamily = Red_Hat_Text({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
  { name: "Home", url: "/" },
  { name: "Stuff", url: "/stuff" },
  { name: "Another Page", url: "/anotherPage" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="/images/favicon.ico" />
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="/images/apple-touch-icon.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/images/favicon-32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/images/favicon-16x16.png"
      />

      <body className={`flex flex-col min-h-screen ${fontFamily.className}`}>
        <Navigation navigation={navigation} />
        <div className="max-w-5xl mx-auto">{children}</div>
        <Footer navigation={navigation} />
      </body>
    </html>
  );
}
